### ISSUE TITLE
Locations & Storage

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#1]
## Resources
* https://developers.google.com/places/
* https://developers.google.com/maps/documentation/javascript/places

## Storage
I think that instead of creating a duplicate Location table and storing results from Google there, we should cache the lat/long/place_id and store it on the relevant Post/Observation. This way, by having the lat/long we don't necessarily have to stick with the Google Places API (although Im not sure of a better alternative), and can utilize any sort of geocoding libs/services available to us.

## Flow
With that in mind, the front end app could use whatever service to do the actual place lookups, it just needs to send to the server a lat/long and (possibly) a google_place_id for storage.

## Considerations
If in a post list each post summary component needs to show the location's name, do we cache that value in a column as well? This would reduce the need for external API lookups on the client to detail views.

**Comment by bradyswenson** [comment]
Yeah this makes sense to me. It's wise to not tie ourselves to one place API. I think we should go ahead and save the Common Place Name for a given Lat/Long. We'll be displaying that with every post.

**Comment by seanwash** [comment]
Closing as we've decided to store all location data in the geojson format which should sufficiently decouple us from any one provider in the future.
