### ISSUE TITLE
Identify Species in New Observation

### ISSUE THREAD

**Issue by bradyswenson** [WatchNature/watchnature_app#17]

**Comment by seanwash** [comment]
## Taxons

### Schema

families (Family) (least specific)
 - id
 - name_scientific
 - name_common

genera (Genus)
 - id
 - family_id
 - name_scientific
 - name_common

species (Species) (most specific)
 - id
 - genus_id
 - name_binomial (genus 'Buteo' + species 'jamaicensis')
 - name_scientific (species name)
 - name_common (Red Tail Hawk | i18n)
 - description
 - image
 
 ### Joins

 observation_families
 observation_genera
 observation_species
